name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Scan Docker Image
    runs-on: windows-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t grafana:latest .

      # Step 4: Scan with Syft
      - name: Scan with Syft
        run: |
          syft grafana:latest

      # Step 5: Scan with Grype
      - name: Scan with Grype
        run: |
          grype grafana:latest --fail-on medium

  deploy:
    name: Deploy to Docker Hub
    runs-on: windows-latest
    needs: build
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.orionsowle }}
          password: ${{ secrets.B@tM@n1996 }}
          

      # Step 3: Push the Docker image
      - name: Push Docker image
        run: |
          docker tag grafana:latest orionsowle/grafana:latest
          docker push orionsowle/grafana:latest